language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  #- openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  #mi linea aqui debajo
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  #los siguientes tres se deben ejecutar en la consola de gclod cli con cada cluster de kubernetes que queramos usar
  - gcloud config set project multi-k8s-328518
  - gcloud config set compute/zone europe-west1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t solamnia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true solamnia/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
